version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.9
    working_directory: ~/repo

jobs:
  setup-and-run-tests:
    executor: python-executor
    steps:
      # Step 1: Checkout medLLM repo
      - checkout

      # Step 2: Install dependencies for medLLM
      - run:
          name: Install Dependencies for medLLM
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            curl "${medLLM_config_file_azure}" -o .env

      # Step 3: Clone BreakYourLLM repository
      - run:
          name: Clone BreakYourLLM Repository
          command: |
            git clone https://${GITHUB_TOKEN}@github.com/ModelPulse/BreakYourLLM.git
            cd BreakYourLLM
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      # Step 4: Replace configurations in BreakYourLLM
      - run:
          name: Replace Configurations
          command: |
            curl "${breakyourllm_config}" -o BreakYourLLM/config/.env
      
      # Step 5: Run main.py in BreakYourLLM
      - run:
          name: Run main.py in BreakYourLLM
          command: |
            cd BreakYourLLM
            . venv/bin/activate
            python main.py

      # Step 6: Check Results
      - run:
          name: Check Results
          command: |
            if grep -q '"status": "error"' BreakYourLLM/results/stage5_metric_evaluation.json; then
              echo "Build Failed"
            else
              echo "Build Passed"
              exit 1
            fi

workflows:
  version: 2
  build-and-test:
    jobs:
      - setup-and-run-tests